### ISSUE TITLE
Data source validator is missing dependency

### ISSUE THREAD

**Issue by jezdez** [mozilla/redash-stmo#34]
Traceback:

```pycon
server_1    | [2019-05-21 15:14:56,057][PID:11][INFO][werkzeug] 172.23.0.1 - - [21/May/2019 15:14:56] "GET /api/query_snippets HTTP/1.1" 200 -
server_1    | Traceback (most recent call last):
server_1    |   File "/usr/local/bin/pgsanity", line 11, in <module>
server_1    |     sys.exit(main())
server_1    |   File "/usr/local/lib/python2.7/dist-packages/pgsanity/pgsanity.py", line 71, in main
server_1    |     return check_files(config.files, add_semicolon=config.add_semicolon)
server_1    |   File "/usr/local/lib/python2.7/dist-packages/pgsanity/pgsanity.py", line 59, in check_files
server_1    |     return check_file(add_semicolon=add_semicolon)
server_1    |   File "/usr/local/lib/python2.7/dist-packages/pgsanity/pgsanity.py", line 32, in check_file
server_1    |     success, msg = check_string(sql_string, add_semicolon=add_semicolon)
server_1    |   File "/usr/local/lib/python2.7/dist-packages/pgsanity/pgsanity.py", line 54, in check_string
server_1    |     success, msg = ecpg.check_syntax(prepped_sql)
server_1    |   File "/usr/local/lib/python2.7/dist-packages/pgsanity/ecpg.py", line 20, in check_syntax
server_1    |     raise OSError(msg)
server_1    | OSError: Unable to execute 'ecpg', you likely need to install it.'
server_1    | [2019-05-21 15:14:56,232][PID:11][INFO][request.summary]
server_1    | [2019-05-21 15:14:56,233][PID:11][INFO][metrics] method=POST path=/api/data_sources/1/validate endpoint=datasourcevalidatorresource status=200 content_type=application/json content_length=30 duration=151.32 query_count=5 query_duration=16.60
server_1    | [2019-05-21 15:14:56,238][PID:11][INFO][werkzeug] 172.23.0.1 - - [21/May/2019 15:14:56] "POST /api/data_sources/1/validate HTTP/1.1" 200 -
```

**Comment by ramesh2744** [comment]
Hi Team,

I'm also facing the same issue.

I used 
Python - 3.9.15
Superset -- 1.5.1
PIP3 - 22.3.1

Please let us know your thought on this error.
**OSError: Unable to execute 'ecpg', you likely need to install it.'**
